import Head from "next/head";

function about() {
    return (
        <div>

            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/img/logo4.png" />
            </Head>

            <section className="mt-[80px]">

                <article className="grid grid-cols-2 mx-[250px]">
                    <header className="col-span-2 my-8">
                        <p className="font-medium text-2xl ">Nuestra Mision</p>
                    </header>
                    <div className="flex col-span-2">
                        <div className="w-[278px] h-[242px] bg-[#D9D9D9] "></div>
                        <div className="w-[450px] ml-5">
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                sequi rem dignissimos illo quibusdam laudantium fugit maxime a sapiente
                                quidem recusandae, ipsam, ratione modi deleniti nostrum quia. Quae, esse asperiores.
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                sequi rem dignissimos illo quibusdam laudantium fugit maxime a sapiente
                            </p>
                        </div>
                    </div>
                </article>

                <article className="flex flex-col justify-center mx-[250px]">
                    <header className="col-span-4">
                        <p className="font-medium text-2xl my-8">Nuestros valores</p>
                    </header>
                    <div className="flex gap-5 ">

                        <article>
                            <header className="w-[160px] h-[160px] bg-gray-300 rounded-full mb-4"></header>
                            <div className="lorem">
                                <p className="">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                    Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                    veritatis illum necessitatibus dolores unde quae similique dolor
                                    corporis sint nam. Sequi, fuga totam!
                                </p>
                            </div>
                        </article>

                        <article>
                            <header className="w-[160px] h-[160px] bg-gray-300 rounded-full mb-4"></header>
                            <div className="lorem">
                                <p className="">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                    Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                    veritatis illum necessitatibus dolores unde quae similique dolor
                                    corporis sint nam. Sequi, fuga totam!
                                </p>
                            </div>
                        </article>

                        <article>
                            <header className="w-[160px] h-[160px] bg-gray-300 rounded-full mb-4"></header>
                            <div className="lorem">
                                <p className="">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                    Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                    veritatis illum necessitatibus dolores unde quae similique dolor
                                    corporis sint nam. Sequi, fuga totam!
                                </p>
                            </div>
                        </article>


                    </div>

                </article>

                <article className="flex flex-col  mx-[250px]">
                    <header>
                        <h3 className="font-medium text-2xl my-8">¿Que te ofrecemos?</h3>
                    </header>

                    <article className="flex mb-14">
                        <div className="flex">
                            <div className="w-[278px] h-[155px] bg-[#D9D9D9] "></div>
                            <div className="w-[450px] ml-5">
                                <p>
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                    sequi rem dignissimos illo quibusdam laudantium fugit maxime a sapiente
                                    quidem recusandae, ipsam, ratione modi deleniti nostrum quia. Quae, esse asperiores.
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                    sequi rem dignissimos illo quibusdam
                                </p>
                            </div>
                        </div>
                    </article>

                    <article className="flex mb-14">
                        <div className="flex flex-row-reverse">
                            <div className="w-[278px] h-[155px] bg-[#D9D9D9] col-start-2 "></div>
                            <div className="w-[450px] ml-5">
                                <p>
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                    sequi rem dignissimos illo quibusdam laudantium fugit maxime a sapiente
                                    quidem recusandae, ipsam, ratione modi deleniti nostrum quia. Quae, esse asperiores.
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                    sequi rem dignissimos illo quibusdam
                                </p>
                            </div>
                        </div>
                    </article>
                </article>

            </section>

            <section className="bg-[#D9D9D9] pb-[50px]">
                <article className="mx-[250px]">
                    <header className="mb-[30px] pt-[23px]">
                        <h3 className="font-medium text-2xl">Nuestro equipo</h3>
                    </header>
                    <div>
                        <ul className="flex justify-between m-0">

                            <li>
                                <header className="font-medium text-xl">Frond</header>
                                <div className="flex flex-col gap-2">
                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>
                                </div>
                            </li>

                            <li>
                                <header className="font-medium text-xl">Back</header>
                                <div className="flex flex-col gap-2">
                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>
                                </div>
                            </li>

                            <li>
                                <header className="font-medium text-xl">Tester</header>
                                <div className="flex flex-col gap-2">
                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                </div>
                            </li>

                            <li>
                                <header className="font-medium text-xl">UX/UI</header>
                                <div className="flex flex-col gap-2">
                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </div>
                </article>
            </section>

        </div>
    )
}

export default about