import Head from "next/head";
import Layout from "../components/Layout";


function contact() {

    const formSubmit = e => {
        e.preventDefault()

        const name = e.target.nameLastname.value
        const subject = e.target.subject.value
        const message = e.target.message.value

        window.location.href = `mailto:valennocountry@gmail.com?subject=${subject}&body=Soy%20${name}%0A${message}`

        e.target.nameLastname.value = ''
        e.target.email.value = ''
        e.target.subject.value = ''
        e.target.message.value = ''

    }

    return (
        <Layout>
            <div className="">

                <Head>
                    <title>Ayuda</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/img/logo4.png" />
                </Head>

                <section className="mx-auto mb-[80px] mt-[140px] w-[95%] max-w-[1024px] ">

                    <header>
                        <h3 className="font-normal text-[30px]">Ayuda/Contacto</h3>
                    </header>

                    <div className="mt-[15px] flex flex-col gap-[15px]">

                        <article>
                            <header>
                                <p className="text-[20px] font-medium">Configuraciones de la cuenta</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">
                                    <a href="#ConfiguracionDeLaCuenta-1" className="text-[#1B5B45]">
                                        Olvidé mi contraseña. ¿Cómo la recupero?
                                    </a>
                                </li>
                                <li className="text-[18px]">
                                    <a href="#ConfiguracionDeLaCuenta-2" className="text-[#1B5B45]">
                                        ¿Cómo puedo cambiar mi contraseña?
                                    </a>
                                </li>
                                <li className="text-[18px]">
                                    <a href="#ConfiguracionDeLaCuenta-3" className="text-[#1B5B45]">
                                        ¿Cómo cambio la imagen de perfil de mi cuenta?
                                    </a>
                                </li>
                            </ul>
                        </article>

                        <article>
                            <header>
                                <p className="text-[20px] font-medium">Compra y venta de productos</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">
                                    <a className="text-[#1B5B45]" href="#Compra/VentaDeProductos-1">
                                        ¿Cómo comprar en Valen?
                                    </a>
                                </li>
                                <li className="text-[18px]">
                                    <a className="text-[#1B5B45]" href="#Compra/VentaDeProductos-2">
                                        Medios de pago disponibles.
                                    </a>
                                </li>
                                <li className="text-[18px]">
                                    <a className="text-[#1B5B45]" href="#Compra/VentaDeProductos-3">
                                        ¿Es seguro comprar en Valen?
                                    </a>
                                </li>
                                <li className="text-[18px]">
                                    <a className="text-[#1B5B45]" href="#Compra/VentaDeProductos-4">
                                        ¿Cuáles son las promociones disponibles?
                                    </a>
                                </li>
                            </ul>
                        </article>

                        <article>
                            <header>
                                <p className="text-[20px] font-medium">Problemas con diseñadores/compradores</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px] ">
                                    <a href="#ProblemasConDiseñadores/Compradores-1" className="text-[#1B5B45]">
                                        No recibí el pedido/pago.
                                    </a>
                                </li>
                                <li className="text-[18px] ">
                                    <a href="#ProblemasConDiseñadores/Compradores-2" className="text-[#1B5B45]">
                                        ¿Cómo realizo el cambio o una devolución?
                                    </a>
                                </li>
                                <li className="text-[18px] ">
                                    <a href="#ProblemasConDiseñadores/Compradores-3" className="text-[#1B5B45]">
                                        ¿Cómo es el proceso de reintegro de dinero?
                                    </a>
                                </li>
                                <li className="text-[18px] ">
                                    <a href="#ProblemasConDiseñadores/Compradores-4" className="text-[#1B5B45]">
                                        Quiero saber el estado de mi cambio/devolución.
                                    </a>
                                </li>
                            </ul>
                        </article>

                        <article>
                            <header>
                                <p className="text-[20px] font-medium">Otras preguntas</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">
                                    <a href="#OtrasPreguntas-1" className="text-[#1B5B45]">
                                        Me gustaría trabajar en Valen.
                                    </a>
                                </li>
                                <li className="text-[18px]">
                                    <a href="#OtrasPreguntas-2" className="text-[#1B5B45]">
                                        Quiero que mi equipo/evento sea sponsoreado por Valen. ¿Cómo los contacto?
                                    </a>
                                </li>
                                <li className="text-[18px]">
                                    <a href="#OtrasPreguntas-3" className="text-[#1B5B45]">
                                        Quiero contratar a Valen para un evento.
                                    </a>
                                </li>
                                <li className="text-[18px]">
                                    <a href="#OtrasPreguntas-4" className="text-[#1B5B45]">
                                        Tengo una sugerencia con respecto a la página. ¿Cómo se las hago llegar?
                                    </a>
                                </li>
                            </ul>
                        </article>

                        <article>
                            <header>
                                <p className="text-[20px] font-medium">Contacto</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">
                                    <a href="#Contacto" className="text-[#1B5B45]">
                                        Necesito ayuda extra. ¿Cómo los puedo contactar?
                                    </a>
                                </li>
                            </ul>
                        </article>

                    </div>

                </section>

                <hr className=" max-w-[1024px] mx-auto w-[95%]" />

                <section className=" max-w-[1024px] mx-auto w-[95%]">

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Configuraciones de la cuenta</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="ConfiguracionDeLaCuenta-1" className="text-[20px] font-bold">Olvidé mi contraseña. ¿Cómo la recupero?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Haz click en “¿olvidaste la contraseña?” en la pantalla de login. Ingresa tu mail registrado para que te envíemos una nueva contraseña de acceso.
                                            Para tu seguridad, en vez de enviarte tu contraseña anterior, crearemos una nueva.
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="ConfiguracionDeLaCuenta-2" className="text-[20px] font-bold">¿Cómo puedo cambiar mi contraseña?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            En tu perfil, haz click en configuración, contraseña y
                                            luego en cambiar contraseña. Confirma la anterior y a continuación escribe la nueva. Te llegará una confirmación al mail registrado.
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="ConfiguracionDeLaCuenta-3" className="text-[20px] font-bold">¿Cómo cambio la imágen de perfil de mi cuenta?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            En tu perfil, haz click en la foto que tienes actualmente,
                                            seleccionar “Subir imagen” y elegir una imágen desde el ordenador y/o dispositivo móvil.
                                        </p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Compra y venta de productos</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="Compra/VentaDeProductos-1" className="text-[20px] font-bold">¿Cómo comprar en Valen?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Comprar en Valen es fácil y seguro. Una vez registrado en el sitio, podes encontrar
                                            los productos destacados de los diseñadores o ingresar una palabra clave en el buscador.
                                            Hacer click en el producto interesado para acceder a los detalles, elegir talle, color y comprar.
                                            Luego de sumarse al carrito de compra, seleccionar el método de envío y hacer click en finalizar compra.
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="Compra/VentaDeProductos-2" className="text-[20px] font-bold">Medios de pago disponibles.</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Aceptamos todas las tarjetas de credito, débito y mercadopago.
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="Compra/VentaDeProductos-3" className="text-[20px] font-bold">¿Es seguro comprar en Valen?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Comprar en Valen es totalmente cómodo, fácil y seguro.
                                            Trabajamos con los más altos estándares de seguridad y toda la información
                                            ingresada en nuestro sitio se mantiene de forma estrictamente confidencial.
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="Compra/VentaDeProductos-4" className="text-[20px] font-bold">¿Cuales son las promociones disponibles?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Las promociones disponibles se ven al momento
                                            de que cada diseñador considere en poner en promoción sus trabajos.
                                            Por lo que al seguir a un diseñador, recibirás vía mail si ha puesto algún
                                            trabajo suyo en descuento.
                                        </p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Problema con diseñadores/compradores</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="ProblemasConDiseñadores/Compradores-1" className="text-[20px] font-bold">No recibí el pedido/pago.</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Cada compra/venta que se realiza en Valen está sujeta al diseñador que
                                            realizó la venta y el comprador del producto por lo que, de haber un problema,
                                            deben solucionarlo por el medio que prefieran.
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="ProblemasConDiseñadores/Compradores-2" className="text-[20px] font-bold">¿Cómo realizo el cambio o una devolución?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Para realizar un cambio o devolución
                                            de un producto es necesario contactarse con el diseñador por
                                            medio de la información de contacto que tiene en su perfil.
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="ProblemasConDiseñadores/Compradores-3" className="text-[20px] font-bold">¿Cómo es el proceso de reintegro de dinero?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            La devolución de dinero la realiza el diseñador al medio de pago utilizado en la compra.
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="ProblemasConDiseñadores/Compradores-4" className="text-[20px] font-bold">Quiero saber el estado de mi cambio/devolución.</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Para verificar el estado del cambio/devolución se debe contactar
                                            con el diseñador para que le brinde la información necesaria.
                                        </p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Otras Preguntas</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="OtrasPreguntas-1" className="text-[20px] font-bold">Me gustaría trabajar en Valen</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Puedes envíarnos tu CV a trabajoenvalen@gmail.com
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="OtrasPreguntas-2" className="text-[20px] font-bold">Quiero que mi equipo/evento sea sponsoreado por Valen. ¿Cómo los contacto?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Para eventos envíarnos un mail con el asunto “sponsor” a eventos@valen.com
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="OtrasPreguntas-3" className="text-[20px] font-bold">Quiero contratar a Valen para un evento.</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Para eventos donde Valen puede participar, enviárnos un mail con el asunto “evento” a eventos@valen.com
                                        </p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p id="OtrasPreguntas-4" className="text-[20px] font-bold">Tengo una sugerencia con respecto a la página. ¿Cómo se las hago llegar?</p>
                                    </header>
                                    <div>
                                        <p className="text-[18px] font-normal">
                                            Puedes dejarnos tus comentarios o demás dudas en el formulario de más abajo.
                                        </p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Contacto</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">Necesito ayuda extra. ¿Cómo los puedo contactar?</p>
                                    </header>
                                    <div>
                                        <p id="Contacto" className="text-[18px] font-normal">
                                            Para cualquier otra duda, problema o sugerencia, por favor dejarla en el formulario de abajo y le contestaremos a la brevedad.
                                        </p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                </section>

                <section className=" mt-[60px] mb-[215px] max-w-[1024px] mx-auto ">
                    <form onSubmit={formSubmit} className="flex flex-col gap-[15px] w-[95%] mx-auto">
                        <div>
                            <label htmlFor="nameLastname">Nombre y apellido</label>
                            <input className="block w-[95%] max-w-[480px] h-[40px] bg-[#F4F0BB] shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] rounded-[8px]" type="text" id="nameLastname" />
                        </div>
                        <div>
                            <label htmlFor="email">E-mail</label>
                            <input className="block w-[95%] max-w-[480px] h-[40px] bg-[#F4F0BB] shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] rounded-[8px]" type="email" id="email" />
                        </div>
                        <div>
                            <label htmlFor="subject">Asunto</label>
                            <input className="block w-[95%] max-w-[480px] h-[40px] bg-[#F4F0BB] shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] rounded-[8px]" type="text" id="subject" />
                        </div>
                        <div className="flex flex-col">
                            <label htmlFor="message">Mensaje</label>
                            <textarea className="w-[95%] max-w-[480px] h-[240px] bg-[#F4F0BB] shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] rounded-[8px]" name="message" id="message" cols="30" rows="10"></textarea>
                        </div>
                        <button className="w-[180px] h-[40px] bg-[#1B5B45] duration-[0.5s] hover:brightness-150  text-white shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] rounded-[16px]">Enviar</button>
                    </form>
                </section>

                <section className="bg-[#1B5B45] pb-[50px]">
                    <article className="flex flex-col max-w-[1024px] mx-auto w-[95%]">
                        <header className="mb-[30px] pt-[23px] self-start ">
                            <h3 className="font-medium text-2xl text-[#F4F0BB]">Nuestro equipo</h3>
                        </header>
                        <div className="">
                            <ul className="flex min-[375px]:flex-wrap gap-[20px] m-0 justify-between text-[#F4F0BB]">

                                <li>
                                    <header className="font-medium text-xl">Frond</header>
                                    <div className="flex flex-col gap-2">
                                        <div>
                                            <p className="font-normal">Barra Gonzalo</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/gonzalo-barra-valle/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                        <div>
                                            <p className="font-normal">Cruz Fabian</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/fabian-cruz-7631a924b/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                        <div>
                                            <p className="font-normal">Martinez Ariel</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/arielstereo" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <header className="font-medium text-xl">Back</header>
                                    <div className="flex flex-col gap-2">
                                        <div>
                                            <p className="font-normal">Aguada Braian</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/braian-aguada/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                        <div>
                                            <p className="font-normal">Cacciolatti Cristian</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/cristiancacciolatti/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <header className="font-medium text-xl">Tester</header>
                                    <div className="flex flex-col gap-2">
                                        <div>
                                            <p className="font-normal">Gerlo Daniela</p>
                                            <p className="font-normal">Link linkedin</p>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <header className="font-medium text-xl">UX/UI</header>
                                    <div className="flex flex-col gap-2">
                                        <div>
                                            <p className="font-normal">Robles Vega Exequiel</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/exequiel-robles-vega-b9432b211/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                        <div>
                                            <p className="font-normal">Vargas Gerardo</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/geravargas/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>
                </section>

            </div>
        </Layout>
    )
}

export default contact