import Head from "next/head";
import Layout from "../components/Layout";


function contact() {
    return (
        <Layout>
            <div>

                <Head>
                    <title>Contacto</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/img/logo4.png" />
                </Head>

                <section className="mx-[250px] my-[80px]">

                    <header>
                        <h3 className="font-normal text-[30px]">Ayuda/Contacto</h3>
                    </header>

                    <div className="mt-[15px] flex flex-col gap-[15px]">

                        <article>
                            <header>
                                <p className="text-[20px]">Configuraciones de la cuenta</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                            </ul>
                        </article>

                        <article>
                            <header>
                                <p className="text-[20px]">Compra y venta de productos</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                            </ul>
                        </article>

                        <article>
                            <header>
                                <p className="text-[20px]">Problemas con diseñadores/compradores</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                            </ul>
                        </article>

                        <article>
                            <header>
                                <p className="text-[20px]">Otras preguntas</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                            </ul>
                        </article>

                        <article>
                            <header>
                                <p className="text-[20px]">Contacto</p>
                            </header>
                            <ul className="list-disc">
                                <li className="text-[18px]">loremp ipsum dolor sit amet</li>
                            </ul>
                        </article>

                    </div>

                </section>

                <hr className="mx-[250px]" />

                <section className="mx-[250px]">

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Configuraciones de la cuenta</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Compra y venta de productos</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Problema con diseñadores/compradores</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Otras Preguntas</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                    <article className="mt-[50px]">
                        <header className="mb-[15px]">
                            <h3 className="text-[20px] font-bold underline">Contacto</h3>
                        </header>
                        <div>
                            <ul className="m-0 flex flex-col gap-[50px]">

                                <li>
                                    <header className="mb-[15px]">
                                        <p className="text-[20px] font-bold">lorem ipsum dolor sit amet</p>
                                    </header>
                                    <div>
                                        <p className="text[18px] font-normal">Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                                            Accusamus magni sunt consectetur ea minus nostrum alias
                                            maiores voluptatem id, sapiente culpa dolor ipsa
                                            consequuntur doloremque repellendus iure, eius hic in.</p>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>

                </section>

                <section className="mx-[250px] mt-[60px] mb-[215px]">
                    <form action="" className="flex flex-col gap-[15px]">
                        <div>
                            <label htmlFor="name/lastname">Nombre y apellido</label>
                            <input className="block w-[480px] h-[40px] bg-[#D9D9D9]" type="text" id="name/lastname" />
                        </div>
                        <div>
                            <label htmlFor="email">E-mail</label>
                            <input className="block w-[480px] h-[40px] bg-[#D9D9D9]" type="email" id="email" />
                        </div>
                        <div>
                            <label htmlFor="subject">Asunto</label>
                            <input className="block w-[480px] h-[40px] bg-[#D9D9D9]" type="text" id="subject" />
                        </div>
                        <div className="flex flex-col">
                            <label htmlFor="message">Mensaje</label>
                            <textarea className="w-[480px] h-[240px] bg-[#D9D9D9]" name="message" id="message" cols="30" rows="10"></textarea>
                        </div>
                        <button className="w-[180px] h-[40px] bg-[#D9D9D9]">Enviar</button>
                    </form>
                </section>

                <section className="bg-[#D9D9D9] pb-[50px]">
                <article className="mx-[250px] flex flex-col">
                    <header className="mb-[30px] pt-[23px] self-start ">
                        <h3 className="font-medium text-2xl">Nuestro equipo</h3>
                    </header>
                    <div className="">
                        <ul className="flex m-0 justify-between ">

                            <li>
                                <header className="font-medium text-xl">Frond</header>
                                <div className="flex flex-col gap-2">
                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>
                                </div>
                            </li>

                            <li>
                                <header className="font-medium text-xl">Back</header>
                                <div className="flex flex-col gap-2">
                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>
                                </div>
                            </li>

                            <li>
                                <header className="font-medium text-xl">Tester</header>
                                <div className="flex flex-col gap-2">
                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                </div>
                            </li>

                            <li>
                                <header className="font-medium text-xl">UX/UI</header>
                                <div className="flex flex-col gap-2">
                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>

                                    <div>
                                        <p className="font-normal">Name</p>
                                        <p className="font-normal">Link linkedin</p>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </div>
                </article>
            </section>

            </div>
        </Layout>
    )
}

export default contact