import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/Layout";
import Slider from "../components/Slider";
import styles from "./../styles/home.module.css";
import { ImStarEmpty } from "react-icons/im";
import { IoIosArrowForward } from "react-icons/io";
import { Avatar, Button } from "@nextui-org/react";

export default function Home({ data }) {

  
  return (
    <Layout>
      <div>
        <Head>
          <title>Valen</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/img/logo4.png" />
        </Head>
        <main className="flex flex-col bg-[#1B5B45] text-center justify-center">
          <div className="mx-auto my-32">
            <Image src="/img/logo2.png" width="400" height="400" alt="logo" />
            <Image
              src="/img/subtitle.png"
              width="200"
              height="200"
              alt="logo"
              className="ml-64"
            />
          </div>
          <Slider />
        </main>
        <section>
          <div className="bg-white">
            {/* Buscador */}
            <div className="px-[600px] py-32">
              <form>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg
                      aria-hidden="true"
                      className="w-8 h-8 text-green-800"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                      ></path>
                    </svg>
                  </div>
                  <input
                    type="search"
                    id="default-search"
                    className="block w-full p-2 pl-16 text-lg text-green-800 border border-gray-300 rounded-xl bg-yellow-100 focus:ring-green-800 focus:border-green-800 "
                    placeholder="Buscar..."
                    required
                  />
                </div>
              </form>
            </div>
            <div className="flex gap-8 ml-36 mb-8">
              <div>
                <Avatar
                  src="https://i.pravatar.cc/150?u=a042581f4e29026024d"
                  color="gradient"
                  bordered
                  css={{ size: "$20" }}
                />
              </div>
              <div className="flex flex-col mx-4">
                <h3 className="text-xl font-semibold">Maxi Man</h3>
                <Button shadow color="success" size="sm" auto>
                  Seguir
                </Button>
              </div>
            </div>
            <div className="flex mx-16">
              {data.slice(0, 3).map(({ price, image, _id , seller}) => (
                <div className={styles.container} key={_id}>
                  
                  {/* Card */}
                  <Image
                    src={image.url}
                    alt="photo"
                    width="800"
                    height="800"
                    className="w-96 h-72"
                  />
                  <div className={styles.icon}>
                    <ImStarEmpty />
                  </div>
                  <div className={styles.text}>{price}</div>
                  <div className="flex mt-2">
                    <div className={styles.circleBlack}></div>
                    <div className={styles.circleGreen}></div>
                    <div className="ml-32">
                      <p className="text-gray-700 text-base font-semibold">
                        Xxl-Xl-L
                      </p>
                    </div>
                  
                  </div>
                  
                </div>
              ))}
              <Link
                href="/designer"
                className="flex flex-col ml-16 text-green-800 hover:text-green-600"
              >
                <IoIosArrowForward className="text-4xl mt-16" />
                <span className="text-xl">Ver más</span>
              </Link>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  try {
    const res = await fetch("http://localhost:3001/products/all");
    const data = await res.json();
    console.log(data);
    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.log(error);
  }
}

