import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>C8-43-MERN!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a>
          No Country 2022
        </a>
      </footer>
    </div>
  )
}
