import Head from "next/head";
import Layout from "../components/Layout";

function about() {
    return (
        <Layout>
            <div>

                <Head>
                    <title>Sobre Nosotros</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/img/logo4.png" />
                </Head>

                <section className="mt-[140px] flex flex-col items-center justify-center w-[95%]  max-w-[1024px] mx-auto">


                    <article className="flex flex-col items-center">
                        <header className="col-span-2 mb-[30px] self-start mx-auto md:ml-0  ">
                            <p className="font-medium text-2xl ">Nuestra Mision</p>
                        </header>
                        <div className="flex flex-wrap gap-[15px] col-span-2 justify-center">
                            <div className="w-[278px] h-[242px] bg-[#D9D9D9] "></div>
                            <div className="w-[80%] mx-auto md:text-start text-center max-w-[450px] ">
                                <p>
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                    sequi rem dignissimos illo quibusdam laudantium fugit maxime a sapiente
                                    quidem recusandae, ipsam, ratione modi deleniti nostrum quia. Quae, esse asperiores.
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                    sequi rem dignissimos illo quibusdam laudantium fugit maxime a sapiente
                                </p>
                            </div>
                        </div>
                    </article>

                    <article className="flex flex-col items-center justify-center ">
                        <header className="col-span-4 self-start m-auto ">
                            <p className="font-medium text-2xl my-8">Nuestros valores</p>
                        </header>
                        <div className="flex flex-wrap gap-[80px] justify-center">

                            <article>
                                <header className="w-[160px] h-[160px] bg-gray-300 rounded-full mb-4 mx-auto "></header>
                                <div className="">
                                    <p className="w-[225px] text-center">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                        veritatis illum necessitatibus dolores unde quae similique dolor
                                        corporis sint nam. Sequi, fuga totam!
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                    </p>
                                </div>
                            </article>

                            <article>
                                <header className="w-[160px] h-[160px] bg-gray-300 rounded-full mb-4 mx-auto "></header>
                                <div className="">
                                    <p className="w-[225px] text-center">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                        veritatis illum necessitatibus dolores unde quae similique dolor
                                        corporis sint nam. Sequi, fuga totam!
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                    </p>
                                </div>
                            </article>

                            <article>
                                <header className="w-[160px] h-[160px] bg-gray-300 rounded-full mb-4 mx-auto "></header>
                                <div className="">
                                    <p className="w-[225px] text-center">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                        veritatis illum necessitatibus dolores unde quae similique dolor
                                        corporis sint nam. Sequi, fuga totam!
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        Totam quaerat nulla magni, doloribus voluptatem odio officia,
                                    </p>
                                </div>
                            </article>

                        </div>

                    </article>

                    <article className="flex flex-col items-center self-center">
                        <header className="self-start m-auto md:ml-0">
                            <h3 className="font-medium text-2xl my-8">¿Que te ofrecemos?</h3>
                        </header>

                        <article className="flex mb-14">
                            <div className="flex flex-wrap gap-4">
                                <div className="w-[278px] h-[155px] bg-[#D9D9D9] m-auto"></div>
                                <div className="w-[80%] text-center max-w-[450px] m-auto">
                                    <p>
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                        sequi rem dignissimos illo quibusdam laudantium fugit maxime a sapiente
                                        quidem recusandae, ipsam, ratione modi deleniti nostrum quia. Quae, esse asperiores.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                        sequi rem dignissimos illo quibusdam
                                    </p>
                                </div>
                            </div>
                        </article>

                        <article className="flex mb-14">
                            <div className="flex flex-wrap flex-row-reverse gap-4">
                                <div className="w-[278px] h-[155px] bg-[#D9D9D9] col-start-2 m-auto"></div>
                                <div className="w-[80%] max-w-[450px] text-center m-auto">
                                    <p>
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                        sequi rem dignissimos illo quibusdam laudantium fugit maxime a sapiente
                                        quidem recusandae, ipsam, ratione modi deleniti nostrum quia. Quae, esse asperiores.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                                        sequi rem dignissimos illo quibusdam
                                    </p>
                                </div>
                            </div>
                        </article>
                    </article>

                </section>


                <section className="bg-[#1B5B45] pb-[50px]">
                    <article className="flex flex-col max-w-[1024px] mx-auto w-[95%]">
                        <header className="mb-[30px] pt-[23px] self-start ">
                            <h3 className="font-medium text-2xl text-[#F4F0BB]">Nuestro equipo</h3>

                        </header>
                        <div className="">
                            <ul className="flex min-[375px]:flex-wrap gap-[20px] m-0 justify-between text-[#F4F0BB]">

                                <li>
                                    <header className="font-medium text-xl">Frond</header>
                                    <div className="flex flex-col gap-2">
                                        <div>
                                            <p className="font-normal">Barra Gonzalo</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/gonzalo-barra-valle/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                        <div>
                                            <p className="font-normal">Cruz Fabian</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/fabian-cruz-7631a924b/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                        <div>
                                            <p className="font-normal">Martinez Ariel</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/arielstereo" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <header className="font-medium text-xl">Back</header>
                                    <div className="flex flex-col gap-2">
                                        <div>
                                            <p className="font-normal">Aguada Braian</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/braian-aguada/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                        <div>
                                            <p className="font-normal">Cacciolatti Cristian</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/cristiancacciolatti/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                    </div>
                                </li>

                                <li>
                                    <header className="font-medium text-xl">Tester</header>
                                    <div className="flex flex-col gap-2">
                                        <div>
                                            <p className="font-normal">Gerlo Daniela</p>
                                            <a target={'_blank'} href='https://linkedin.com/in/daniela-gerlo' className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <header className="font-medium text-xl">UX/UI</header>
                                    <div className="flex flex-col gap-2">
                                        <div>
                                            <p className="font-normal">Robles Vega Exequiel</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/exequiel-robles-vega-b9432b211/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>

                                        <div>
                                            <p className="font-normal">Vargas Gerardo</p>
                                            <a target={"_blank"} href="https://linkedin.com/in/geravargas/" className="font-normal text-[#F4F0BB]">Link linkedin</a>
                                        </div>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </article>
                </section>

            </div>
        </Layout>
    )
}

export default about